name: CICD Pipeline

on:
push:
branches: ["main"]

pull_request:
branches: ["main"]

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v5

  - name: Set up JDK 17
    uses: actions/setup-java@v5
    with:
      java-version: "17"
      distribution: "temurin"
      cache: maven
      cache-dependency-path: cicd/pom.xml

  - name: Build with Maven
    working-directory: ./cicd
    run: mvn -B package

  - name: Trivy Security Scan
    uses: aquasecurity/trivy-action@master
    with:
      scan-type: fs
      scan-ref: .
      format: table

